import type { NeoTheme } from "./types";

export const defaultTheme: NeoTheme = {
  colors: {
    surface: "#fcf8f7",
    surfaceDim: "#ddd9d8",
    surfaceBright: "#fcf8f7",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerLow: "#f7f3f2",
    surfaceContainer: "#f1edec",
    surfaceContainerHigh: "#ebe7e6",
    surfaceContainerHighest: "#e5e2e1",
    onSurface: "#1c1b1b",
    onSurfaceVariant: "#444844",
    inverseSurface: "#313030",
    inverseOnSurface: "#f4f0ef",
    background: "#fcf8f7",
    onBackground: "#1c1b1b",
    primary: "#FFD54F",
    onPrimary: "#1c1b1b",
    primaryContainer: "#fff8d6",
    onPrimaryContainer: "#464745",
    secondary: "#E9D5FF",
    onSecondary: "#1c1b1b",
    secondaryContainer: "#f3eaff",
    onSecondaryContainer: "#464745",
    tertiary: "#A7F3D0",
    onTertiary: "#1c1b1b",
    tertiaryContainer: "#d1fce6",
    onTertiaryContainer: "#464745",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdad6",
    onErrorContainer: "#93000a",
    outline: "#757874",
    outlineVariant: "#c5c7c3",
  },
  shadows: {
    sm: "2px 2px 0px 0px rgba(26, 26, 26, 1)",
    md: "4px 4px 0px 0px rgba(26, 26, 26, 1)",
    lg: "6px 6px 0px 0px rgba(26, 26, 26, 1)",
    inset: "inset 2px 2px 0px 0px rgba(26, 26, 26, 1)",
  },
  borders: {
    width: 2,
    color: "#1c1b1b",
  },
  radii: {
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1.25rem",
    full: "9999px",
  },
  typography: {
    displayFont: '"Fredoka", "Quicksand", sans-serif',
    bodyFont: '"Quicksand", sans-serif',
    labelFont: '"Work Sans", "Quicksand", sans-serif',
  },
  motion: {
    duration: "0.1s",
    easing: "ease",
  },
};
